# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c9d34ae1b402e8312a34176e0a2d02800b936a89c4794f500387067714f6b0f3dc0d54fc6c064c841af3512403eaaacbea5023f31d056c11235856e0ed3858e

test:
  secret_key_base: f8c93bec51c82f8e2735c4d546a269ccc378f17e3ed406141f9679fa6a7de493c356f5f5ae78133007e57f013a6f291389f2b3de4774a9990b13f0e6f63882c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
